name: Run gulp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependecies
        run: yarn --frozen-lockfile

      - name: Run build script
        run: yarn build

      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git add -A
          git commit -m "Run gulp"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_GITHUB_TOKEN }}